/**
 * Password verification and tokens, without a database.
 *
 * The password fixtures were produced by Django itself (see
 * `__fixtures__/django_hashes.json`), not by the code under test. That is the
 * whole point: a verifier tested only against hashes it generated would pass
 * happily while misreading every real row in `auth_user`.
 */

import assert from 'assert';
import { test, describe, finish } from '../scoring/harness';
import { verifyDjangoPassword, parseDjangoHash } from './djangoPassword';
import { issueToken, readToken, bearerFrom } from './tokens';

// Imported rather than required so tsc resolves it and copies it into the
// build output alongside the compiled test.
import fixtures from './__fixtures__/django_hashes.json';

describe(`django password hashes (generated by Django ${fixtures.djangoVersion})`);

for (const { password, encoded } of fixtures.cases) {
    const iterations = encoded.split('$')[1];

    test(`accepts the right password at ${iterations} iterations`, () => {
        assert.strictEqual(verifyDjangoPassword(password, encoded), true);
    });

    test(`rejects a wrong password at ${iterations} iterations`, () => {
        assert.strictEqual(verifyDjangoPassword(password + 'x', encoded), false);
        assert.strictEqual(verifyDjangoPassword(password.toUpperCase() + '!', encoded), false);
    });
}

test('reads the cost from the hash rather than assuming one', () => {
    // Accounts on the real database carry different iteration counts, so a
    // hardcoded cost would reject everyone created under a different Django.
    const seen = new Set(fixtures.cases.map((c) => parseDjangoHash(c.encoded)!.iterations));
    assert.ok(seen.size >= 2, `expected several iteration counts, saw ${[...seen].join(', ')}`);
});

test('rejects a tampered hash', () => {
    const { password, encoded } = fixtures.cases[0];
    const parts = encoded.split('$');
    parts[3] = parts[3].slice(0, -2) + (parts[3].endsWith('A') ? 'BB' : 'AA');
    assert.strictEqual(verifyDjangoPassword(password, parts.join('$')), false);
});

test('rejects a hash whose cost was altered', () => {
    const { password, encoded } = fixtures.cases[0];
    const parts = encoded.split('$');
    parts[1] = '1000';
    assert.strictEqual(verifyDjangoPassword(password, parts.join('$')), false);
});

test('refuses anything it does not understand instead of throwing', () => {
    assert.strictEqual(verifyDjangoPassword('x', ''), false);
    assert.strictEqual(verifyDjangoPassword('x', 'not-a-hash'), false);
    assert.strictEqual(verifyDjangoPassword('x', 'a$b$c'), false);
    assert.strictEqual(verifyDjangoPassword('x', 'argon2$v=19$m=102400,t=2,p=8$salt$hash'), false);
    assert.strictEqual(verifyDjangoPassword('', fixtures.cases[0].encoded), false);
});

describe('tokens');

process.env.JWT_SECRET = 'a'.repeat(48);

test('a token round-trips its claims', () => {
    const token = issueToken({ sub: 14, username: 'data_entry', isStaff: true });
    const claims = readToken(token);
    assert.ok(claims);
    assert.strictEqual(claims!.sub, 14);
    assert.strictEqual(claims!.username, 'data_entry');
    assert.strictEqual(claims!.isStaff, true);
});

test('a non-staff token keeps its flag', () => {
    const claims = readToken(issueToken({ sub: 2, username: 'edsonc', isStaff: false }));
    assert.strictEqual(claims!.isStaff, false);
});

test('a token signed with another secret is refused', () => {
    const token = issueToken({ sub: 1, username: 'pjlenhart', isStaff: true });
    process.env.JWT_SECRET = 'b'.repeat(48);
    assert.strictEqual(readToken(token), null);
    process.env.JWT_SECRET = 'a'.repeat(48);
});

test('garbage is refused rather than throwing', () => {
    assert.strictEqual(readToken(''), null);
    assert.strictEqual(readToken('not.a.token'), null);
    assert.strictEqual(readToken('a.b.c'), null);
});

test('a short or missing secret disables signing rather than defaulting', () => {
    const saved = process.env.JWT_SECRET;

    delete process.env.JWT_SECRET;
    assert.throws(() => issueToken({ sub: 1, username: 'x', isStaff: true }), /JWT_SECRET/);

    process.env.JWT_SECRET = 'tooshort';
    assert.throws(() => issueToken({ sub: 1, username: 'x', isStaff: true }), /JWT_SECRET/);

    process.env.JWT_SECRET = saved;
});

test('pulls a bearer token out of the header', () => {
    assert.strictEqual(bearerFrom('Bearer abc.def.ghi'), 'abc.def.ghi');
    assert.strictEqual(bearerFrom('bearer abc'), 'abc');
    assert.strictEqual(bearerFrom('Basic abc'), '');
    assert.strictEqual(bearerFrom(undefined), '');
});

finish();
